[general]
import = ["kanagawa.toml", "keymaps.toml"]

[window]
decorations = "None"
title = "Matchew Terminal"
resize_increments = true

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Hack Nerd Font Mono", style = "Bold Italic" }
size = 13.50

[selection]
save_to_clipboard = true
