call plug#begin()
Plug 'morhetz/gruvbox'
Plug 'itchyny/lightline.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-vinegar'
call plug#end()

" line numbers
set number
set relativenumber
set cursorline

" color scheme
set background=dark
colorscheme gruvbox

" statusline config
set laststatus=2
set noshowmode
let g:lightline = { 'colorscheme': 'wombat', }

" fzf keybinds
nnoremap <leader>sf :Files<CR>
nnoremap <leader>sl :BLines<CR>
nnoremap <leader>sb :Buffers<CR>
nnoremap <leader>sh :History<CR>

" vin remaps
nnoremap <leader>e :e .<CR>
