export LANG=en_US.UTF-8
export EDITOR='nvim'

export MANPATH="/usr/local/man:$MANPATH"
export PATH=$PATH:$HOME/go/bin # add go to path
export PATH="$HOME/.luarocks/bin:$PATH" # add luarocks to path
export PATH="$HOME/.npm-global/bin:$PATH" # add npm to path
export PATH="$HOME/.cabal/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

[ -f "/home/matchew/.ghcup/env" ] && . "/home/matchew/.ghcup/env"

HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=50000
setopt hist_ignore_dups # ignore saving dup cmds
setopt hist_ignore_space # dont save cmd is starts w/ space
setopt append_history
setopt share_history
setopt auto_cd

source <(fzf --zsh)
bindkey -v

autoload -Uz compinit && compinit

ff() {
	firefox --new-tab "$@" > /dev/null 2>&1 & disown
}

# config this
alias email="ff https://mail.google.com/mail/u/0/#inbox"

alias canvas="ff https://canvas.uw.edu/"

# config this?
alias github="ff https://github.com/"

alias vi='nvim'
alias g='git'

# (learn how to use this)
alias ls='eza'
alias grep='rg'
alias top='htop'
alias cat='bat'
alias find='fd'

cdf() {
  local dir
  dir=$(fd --type d --hidden --follow . | fzf) || return  # fuzzy find a directory
  if [[ -n "$dir" ]]; then
    cd "$dir" || echo "Failed to cd into $dir"
  fi
}

fe() {
  local file
  file=$(fzf) || return   # fuzzy find a file
  if [[ -n "$file" ]]; then
    vi "$file"
  fi
}

# cd ... (look into other zsh specific stuff)
up() {
  local n=${1:-1}
  for ((i = 0; i < n; i++)); do
    cd ..
  done
}

export STARSHIP_CONFIG=~/.config/starship/starship.toml
ZSH_PLUGIN_PATH=/usr/share/zsh/plugins
source $ZSH_PLUGIN_PATH/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSH_PLUGIN_PATH/zsh-history-substring-search/zsh-history-substring-search.zsh

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey '^P'   history-substring-search-up
bindkey '^N'   history-substring-search-down

# jq, zioxide, gh, fzf

# can do this with git config?
# alias rm='trash'
# (zioxide tool)
# (fd tool)
# (gh cli)
# (doppler cli)
# (pass)
# (jq)
# (stow)
# (fzf)
# unbind rm for trash-cli?
#
# make a function to write all arch downloads to a folder
# make a up function that lets me go up n directories
# minimize config and pacman install stuff

# get around vi mode bug
type starship_zle-keymap-select >/dev/null || \
{
  eval "$(starship init zsh)"
}

# export VISUAL="nvim"
# export PAGER="less"
#
# autoload -Uz colors && colors
# PROMPT='%F{green}%n@%m%f:%F{blue}%~%f %# '
#
# alias ls='ls --color=auto'
# alias ll='ls -lh'
# alias la='ls -A'
# alias l='ls -CF'
# alias cls='clear'
# alias ..='cd ..'
# alias ...='cd ../..'
# alias grep='grep --color=auto'
# alias vim='nvim'
#
# git stauts -> gs and etc

[[ ! -r '/home/matchew/.opam/opam-init/init.zsh' ]] || source '/home/matchew/.opam/opam-init/init.zsh' > /dev/null 2> /dev/null
