if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh" # installer

ZSH_THEME="powerlevel10k/powerlevel10k"

zstyle ':omz:update' mode reminder
zstyle ':omz:update' frequency 7

HYPHEN_INSENSITIVE="true"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="mm/dd/yyyy"

plugins=(zsh-syntax-highlighting colored-man-pages)

# zoxide – smarter cd, jump to frequently used directories.
# gitfast – Git aliases and completion (fast version with fewer zsh-specific features).
# gh – GitHub CLI completion.
# fzf – fuzzy finder with key bindings for autocompletion and searching.
# fzf-tab – fancy tab completions using fzf.
# history-substring-search – search command history by typing substring
# vi-mode – vi-like keybindings in the shell.
# command-not-found – suggests packages if a command isn’t found.
# colorize – syntax-highlight file contents (300+ languages).
# rust – completion for Rust (rustc, cargo, rustup).
# ssh-agent – automatically start ssh-agent and load credentials.
# starship – modern, fast, customizable prompt.
# tmux – aliases and helpers for tmux.
# web-search – quick search aliases for Google, Wiki, Bing, YouTube, etc
# autocomplete, zsh completions

source $ZSH/oh-my-zsh.sh

# User configuration

export MANPATH="/usr/local/man:$MANPATH"

export LANG=en_US.UTF-8
export EDITOR='nvim'

source <(fzf --zsh)

UPDATE_FILE="$ZSH_CUSTOM/.last_pacman_update"
NOW=$(date +%s)
ONE_WEEK=$((60 * 60 * 24 * 7))
if [[ ! -f "$UPDATE_FILE" || $((NOW - $(cat "$UPDATE_FILE"))) -ge $ONE_WEEK ]]; then
	echo "Consider running sudo pacman -Syu"
	echo "$NOW" > "$UPDATE_FILE"
fi

# make a function to write all arch downloads to a folder
# make a up function that lets me go up n directories

alias ff="firefox >/dev/null 2>&1 & disown"
alias vim='nvim'

# minimize config and pacman install stuff

alias ls='eza -alh --group-directories-first --icons'
alias ga='git add'
alias gc='git commit'
alias gs='git status'
alias gp='git push'

cdf() {
  local dir
  dir=$(find . -type d | fzf) || return  # fuzzy find a directory
  if [[ -n "$dir" ]]; then
    cd "$dir" || echo "Failed to cd into $dir"
  fi
}

fe() {
  local file
  file=$(fzf) || return   # fuzzy find a file
  if [[ -n "$file" ]]; then
    nvim "$file"
  fi
}

bindkey -v # vimode

# unbind rm for trash-cli?

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/dotfiles/zsh/p10k.zsh ]] && source ~/dotfiles/zsh/p10k.zsh
