#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '
alias tagr='ctags -R --languages=Rust --exclude=target .'

export STARSHIP_CONFIG=~/dotfiles/starship/starship.toml
export EDITOR=vim

eval "$(starship init bash)"
eval "$(fzf --bash)"

set -o vi

# ripgrep
# fzf

. "$HOME/.cargo/env"

[ -f "/home/matchew/.ghcup/env" ] && . "/home/matchew/.ghcup/env"
